name: rfc_3339_date_time_serializer
description: >
  RFC 3339 DateTime serializer for built_value.
  To address the issue with datetimes with more than 6 characters in time-secfrac.
version: 1.0.1
homepage: https://github.com/Albert221/rfc_3339_date_time_serializer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_value: ^7.0.0

dev_dependencies:
  test: ^1.0.0
